config/routes.rb
Gallery::Application.routes.draw do
  devise_for :users

  

  root :to => "home#index"
  resources :photo_collections, :path => 'photos', :except => :show
  get 'own_collections' => 'photo_collections#my_collections'
  get 'galleries' => 'photo_collections#galleries'
  get 'photos/:token' => 'photo_collections#show'
  match "*path" => 'errors#handle404', :via => :get
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :name, :file, :remote_file_url

  belongs_to :attachable, :polymorphic => true
  mount_uploader :file, FileUploader
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/models/photo_collection.rb
class PhotoCollection < ActiveRecord::Base
	include Tokenable
	validates :name, presence: true
	belongs_to :user
	attr_accessible :name, :description, :attachments_attributes
	has_many :attachments, :as => :attachable, :dependent => :destroy
  	accepts_nested_attributes_for :attachments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #setup accessible attribute for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :photo_collections

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'active_record/errors'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_filter :authenticate_user!
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	def handle404
		render :template => "shared/404"
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		sleep 1 if request.xhr?
		@photo_collections = PhotoCollection.paginate(:per_page => 7, :page => params[:page])
	end
end

app/controllers/photo_collections_controller.rb
class PhotoCollectionsController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]  
	def index
		sleep 1 if request.xhr?
		@photo_collections = PhotoCollection.paginate(:per_page => 7, :page => params[:page])
	end

	def my_collections
		sleep 1 if request.xhr?
		@photo_collections = current_user.photo_collections.paginate(:per_page => 7, :page => params[:page])
	end

	def galleries
		@photo_collections = PhotoCollection.all
	end
	
	def new
		@photo_collection = PhotoCollection.new 
	end

	def create
	 	@photo_collection = PhotoCollection.new(params[:photo_collection])
	 	@photo_collection.user_id = current_user.id
	 	if @photo_collection.save
  			redirect_to photo_collection_path(@photo_collection.token)
		else
  			render :new 
		end
	end

	def edit
		@photo_collection = PhotoCollection.find(params[:id])
		render :template => 'photo_collections/new'
	end

	def update
		@photo_collection = PhotoCollection.find(params[:id])
		@photo_collection.update_attributes(params[:photo_collection])
		@photo_collection.user_id = current_user.id
	 	if @photo_collection.save
  			redirect_to photo_collection_path(@photo_collection.token)
		else
  			redirect_to edit_photo_collection_path(@photo_collection.id) 
		end
	end

	def show
		@photo_collection = PhotoCollection.find_by_token(params[:token])
	end

	def destroy
		@photo_collection = PhotoCollection.find(params[:id])
		@photo_collection.destroy
		redirect_to photo_collections_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_collections_helper.rb
module PhotoCollectionsHelper
end

app/views/home/index.html.erb
<%= javascript_include_tag "pagination" %>
<div style="float:left;">
	<b><%= link_to 'Add New photo collections', new_photo_collection_path %></b>
</div>
<% if current_user %>
	<div style="float:right;margin-right:5px;">
		Logged in as <%= current_user.email if current_user %>
		&nbsp; <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
	</div>
<% end %>
<div style="clear:both;"></div>
<div id="photo-collections" style="margin: 5px;">
	<%= render 'photo_collections/photo_collections' %>
</div>

<script type="text/javascript">
	$(".fancybox").fancybox({
	   helpers : { 
	    title : { type : 'inside' }
	   }, // helpers
	   beforeLoad: function() {
	    this.title = $(this.element).attr('title');
	   }
	}); // fancybox
</script>

app/views/home/index.js.erb
$("#photo-collections").html("<%= escape_javascript(render("photo_collections/photo_collections")) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %> 
  <%= javascript_include_tag "nested_form","jquery.fancybox", "jquery.fancybox.pack" %>
</head>
<body>
<div id="wrapper">
  <div id="wrapper-top"> </div>
  <div id="left">
    <h1 class="logo"><%= link_to "Gallery", root_path %></h1>
    <ul class="menu">
      <li> 
      	<a href="/photos">Photo Collections</a>
      </li>
      <li> 
        <%= link_to "My Photo Collections", own_collections_path %>
      </li>
      <li> 
        <%= link_to "Image Galleries", galleries_path %>
      </li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
  <div id="right">
    <div style="margin-left:10px;">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
  <div id="wrapper-bottom"> </div>
  </div>
</body>
</html>

app/views/photo_collections/_image.html.erb
 <%= cl_image_tag(image.file.url(:thumbnail).to_s) %>

app/views/photo_collections/_photo_collections.html.erb
<%= javascript_include_tag "pagination" %>
<%= will_paginate @photo_collections %>
  <table cellpadding=0 cellspacing=0 width="98%">
	<th>Collection Name</th>
	<th>Collection Description</th>
	<th>Collection Photos</th>
	<th>Created at</th>
	<th>&nbsp;Edit</th>
	<th>&nbsp;Delete</th>
	<th>&nbsp;View</th>
	<% @photo_collections.each do |collection| %>
	<tr valign="top">
	 <td><%= link_to collection.name, photo_collection_path(collection.token) %></td>
	 <td><%= collection.description %></td>
	 <td>
	 <% collection.attachments.each do |attachment| %>
	    <%=link_to(cl_image_tag(attachment.file.url(:thumbnail).to_s), attachment.file.url, :data => { :'fancybox-group' => 'gallery' }, :class => "fancybox", :title => "#{attachment.name}-#{attachment.created_at.strftime('%d %b. %Y')}") %>
	 <% end %>
	</td>
	<td>&nbsp;<%= collection.created_at.strftime("%d %b. %Y") %></td>
	<% if current_user && current_user.id == collection.user.id %>
		<td>
			&nbsp;<%= link_to 'edit',edit_photo_collection_path(collection.id) %>
		</td>
		<td>
			&nbsp;<%= link_to "Delete", photo_collection_path(collection.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
		</td>
	<% else %>
		<td>&nbsp;&nbsp;No Permission</td>
		<td>&nbsp;&nbsp;No Permission</td>
	<% end %>
	<td>
		<%= link_to "view", photo_collection_path(collection.token) %>
	</td>
	</tr>
	<% end %>
  </table>
<%= will_paginate @photo_collections %>
<script type="text/javascript">
	$(".fancybox").fancybox({
	   helpers : { 
	    title : { type : 'inside' }
	   }, // helpers
	   beforeLoad: function() {
	    this.title = $(this.element).attr('title');
	   }
	}); // fancybox
</script>

app/views/photo_collections/_photo_galleries.html.erb
<% @photo_collections.each do |collection| %>
   <% collection.attachments.each do |attachment| %>
    <li>
      <%=link_to(cl_image_tag(attachment.file.url(:standard).to_s), attachment.file.url, :data => { :'fancybox-group' => 'gallery' },:rel => "gallery", :class => "fancybox", :width => "150", :height => "121", :title => "#{attachment.name}-#{attachment.created_at.strftime('%d %b. %Y')}") %>
    </li>
   <% end %>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
	$(".fancybox").fancybox({
	   helpers : { 
	    title : { type : 'inside' }
	   }, // helpers
	   beforeLoad: function() {
	    this.title = $(this.element).attr('title');
	   }
	}); // fancybox
  });
</script>

app/views/photo_collections/galleries.html.erb
<div>
    <ul class="thumbnails">
      <%= render 'photo_galleries', :collection => @photo_collections %>
    </ul>
</div>
  

app/views/photo_collections/index.html.erb
<h2>Photo Collections:</h2>
<%= javascript_include_tag "pagination" %>
<div style="float:left;">
	<b><%= link_to 'Add New photo collections', new_photo_collection_path %></b>
</div>
<% if current_user %>
	<div style="float:right;margin-right:5px;">
		Logged in as <%= current_user.email if current_user %>
		&nbsp; <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
	</div>
<% end %>
<div style="clear:both;"></div>
<div id="photo-collections">
	<%= render 'photo_collections' %>
</div>

app/views/photo_collections/index.js.erb
$("#photo-collections").html("<%= escape_javascript(render("photo_collections")) %>");

app/views/photo_collections/my_collections.html.erb
<h2>My Photo Collections:</h2>
<%= javascript_include_tag "pagination" %>
<div style="float:left;">
	<b><%= link_to 'Add New photo collections', new_photo_collection_path %></b>
</div>
<div style="float:right;margin-right:5px;">
	Logged in as <%= current_user.email %>
	&nbsp; <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
</div>
<div style="clear:both;"></div>
<div id="photo-collections">
	<%= render 'photo_collections' %>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $(".fancybox").fancybox();
    });
</script>

app/views/photo_collections/new.html.erb
<%= nested_form_for @photo_collection, :html=>{:multipart => true } do |f| %>
  <% if @photo_collection.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@photo_collection.errors.count, "error") %> prohibited this photo collection from being saved:</h2>
    <ul>
    <% @photo_collection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </p>
  <p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
  </p>
  <%= f.fields_for :attachments do |attachment_form|  %>
    <%= attachment_form.hidden_field(:file_cache) %>
    <p>
    <%= attachment_form.label :image_caption %><br />
    <%= attachment_form.text_field :name %>
    </p>
    <p>
    <%= attachment_form.label :file %><br />
    <%= attachment_form.file_field :file %>
    </p>
    <p>
      <%= attachment_form.label :remote_file_url, "or Image URL" %><br />
      <%= attachment_form.text_field :remote_file_url %>
    </p>
    <%= cl_image_tag(attachment_form.object.file.url(:thumbnail).to_s) if attachment_form.object.present? && attachment_form.object.file.present? %>
    <%= attachment_form.link_to_remove "Remove this attachment" %>
  <% end %>
  <%= f.link_to_add "Add attachment", :attachments %>
  <p><%= f.submit %></p>
 <% end %>

app/views/photo_collections/show.html.erb
<div style="float:left;">Name : &nbsp; <%= @photo_collection.name %></div>
<div style="float:right;margin-right:5px;">Created at : &nbsp;<%= @photo_collection.created_at.strftime("%d %b. %Y") %></div>
<div style="clear:both;"></div>
<div>
	Description : &nbsp; <%= @photo_collection.description %>
</div>
<div style="float:right;margin-right:5px;"> 
<% if current_user && current_user.id == @photo_collection.user.id %>
<table>
	<tr>
		<td>
			&nbsp;<%= link_to 'edit',edit_photo_collection_path(@photo_collection.id) %>
		</td>
		<td>
			&nbsp;<%= link_to "Delete", photo_collection_path(@photo_collection.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
		</td>
	</tr>
</table>
<% end %>
</div>
<div style="clear:both;"></div>
<div>
<ul class="thumbnails">
   <% @photo_collection.attachments.each do |attachment| %>
    <li>
      <%=link_to(cl_image_tag(attachment.file.url(:standard).to_s), attachment.file.url, :data => { :'fancybox-group' => 'gallery' },:rel => "gallery", :class => "fancybox", :width => "150", :height => "121", :title => "#{attachment.name}-#{attachment.created_at.strftime('%d %b. %Y')}") %>
    </li>
   <% end %>
</ul>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $(".fancybox").fancybox({
		   helpers : { 
		    title : { type : 'inside' }
		   }, // helpers
		   beforeLoad: function() {
		    this.title = $(this.element).attr('title');
		   }
  		}); // fancybox
    });
</script>

app/views/shared/404.html.erb
<div> Page Not found </div>